### ISSUE TITLE
Please add sample data

### ISSUE THREAD

**Issue by pcav** [geometalab/Editable-GeoCSV-QGIS-Plugin#1]
For easier testing and understanding.

**Comment by faustos** [comment]
Sorry for the long response time. I needed to wait for the latest plugin version to be approved to match the current GeoCSV spec. The newest version 0.8.2 should be compliant with the examples provided on the GeoCSV spec website (http://giswiki.hsr.ch/GeoCSV). The sample GeoCSV files (.csv with corresponding .csvt and .prj) can also be found in the project's test folder on github (https://github.com/geometalab/Editable-GeoCSV-QGIS-Plugin/tree/master/test/testresources).

I will close this issue in addition to this comment. Please reopen this issue or contact us directly if you need any additional information.

**Comment by sfkeller** [comment]
Seems that with version 1.0.0 the template files aren't included (again).

**Comment by faustos** [comment]
Will be resolved in next Version 1.0.1.
