### ISSUE TITLE
Plugin installation breaks when User Locale is NULL

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Editable-GeoCSV-QGIS-Plugin#4]
When trying to install the Editable GeoCSV plugin following error occurred:
  "the plugin is broken. Python said:
  'QPyNullVariant' object has no attribute '**getitem**'

The plugin has this line: 
  locale = QSettings().value('locale/userLocale')[0:2] 
... which is crashing because it gets NULL and then tries to slice it and fails. 

For some reason that setting is null when the plugin asks for it although the options report one. It is unclear why. In any case the plugin could set a default value if return value is NULL.

See also the original post on Qgis-user mailinglist including Nathan's workaround about "Editable GeoCSV": https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg31157.html

**Comment by faustos** [comment]
Will be resolved in next version 1.0.1.
